orient p
rese
#
load ni,test.nipl
load ni,test.nipl
load ni,test.nipl
#
glat 2,7
smooth 3,7
#
hlin 1,100,50,20
hcol 1,1,3
hcol 2,1,3
hcol 3,1,3
#
achx [h h 0]
achy [0 0 l]
fnam off
aver 0.707
skal 0.35,1.85,3.20,4.50
mark 0.5,0.5
buf 0.055
#
nfra 3
sfra 1,0.0,0.6,1.0,0.9
sfra 2,0.0,0.3,1.0,0.6
sfra 3,0.0,0.0,1.0,0.3
#
afra 1
kfra 1,1
tit2 Raw data
#
afra 2
kfra 2,2
tit2 'glat'
#
afra 3
kfra 3,3
tit2 'smooth'
#
plot
