#
rese
orient port
#
load xy,test.xy
#
achx OFF
achy y-axis [units]
#
grid off
fnam off
#
lcol 1,3
lwid 1,0.5
mtyp 1,3
mcol 1,1
msiz 1,0.3
#
skal -2.5,6.5,-5.5,29.5
mark 1,10
fset 2
#
nfra 3
sfra 1,0.0,0.0,1.0,0.3
sfra 2,0.0,0.3,1.0,0.5
sfra 3,0.0,0.5,1.0,0.8
#
afra 3
buff 0.1,0.1,0.0,0.1
lart 1,1
sann 1,"lart 1",-2,20
#
afra 2
buff 0.1,0.1,0.0,0.0
lart 1,2
sann 1,"lart 2",-2,20
#
afra 1
buff 0.1,0.1,0.1,0.0
lart 1,3
achx x-axis [units]
sann 1,"lart 3",-2,20
#
