rese
i[0]=$1
load sc, DIFFEV/Summary, 1, 1,(i[0]-1)*4 + 6
load sc, DIFFEV/Summary, 1, 1,(i[0]-1)*4 + 7
load sc, DIFFEV/Summary, 1, 1,(i[0]-1)*4 + 8
load sc, DIFFEV/Summary, 1, 1,(i[0]-1)*4 + 9
#kcal add,1,4
#kcal sub,1,4
mtyp 1,3
mtyp 2,3
mtyp 3,3
#kmtyp 5,3
#kmtyp 6,3
mcol 1,3
mcol 2,1
mcol 3,1
#kmcol 5,3
#kmcol 6,3
lcol 1,3
lcol 2,1
lcol 3,1
ltyp 1,1
ltyp 2,1
ltyp 3,1
#klcol 5,3
#klcol 6,3
kfra 1, 1,2,3
#kfra 1, 1,2,3,5,6
skal
plot
