kuplot
#
rese
buff 0.12,0.12,0.12,0.05
#
load xy, DATA/zno.grobs
nfra 2
sfra 1, 0.00, 0.00, 1.00, 1.00
sfra 2, 0.30, 0.41, 0.96, 0.96
kfra 1, 1
kfra 2, 1
#
afra 1
fnam off
font size,3,18
font size,4,18
skal  0, 50, -4, 11
mark  10, 5
achx Distance [\A]
achy G(r) [\A\u-2\d]
lcol 1,3
lwidt 1,0.1
#
afra 2
skal 35, 40
mark 5, 0.05
achx
achy
plot
save ps, nano_data.ps
sys ps2epsi nano_data.ps
system mv nano_data.epsi ../../pic
 
exit
